services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: pace_db
    volumes:
      - local_pgdata:/var/lib/postgresql
    networks:
      - pace_network

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - pace_network

volumes:
  local_pgdata:
  pgadmin-data:
  redis-data:

networks:
  pace_network:
